import React from 'react';
import { BarChart3, TrendingUp, AlertCircle, CheckCircle2, Lightbulb, ShieldCheck } from 'lucide-react';

const BusinessSummaryCard = ({ payload }) => {
  if (!payload) return null;

  return (
    <div className="ew-custom-card" style={{ width: '100%', maxWidth: '600px' }}>
      <div className="ew-card-header" style={{ borderBottom: '1px solid var(--border)', paddingBottom: '12px', marginBottom: '16px' }}>
        <div className="ew-card-icon-wrapper" style={{ background: 'var(--accent-light)', color: 'var(--accent)' }}>
          <BarChart3 size={18} strokeWidth={2.5} />
        </div>
        <div className="ew-card-title-group">
          <span className="ew-card-title">Executive Business Summary</span>
          <span className="ew-card-subtitle">Generated by Super Agent</span>
        </div>
      </div>

      <div className="ew-card-body" style={{ padding: '0 4px' }}>
        {payload.overall_health && (
          <div style={{ marginBottom: '20px', padding: '12px', background: 'var(--bg-hover)', borderRadius: '6px', border: '1px solid var(--border)' }}>
            <h4 style={{ margin: '0 0 4px 0', fontSize: '13px', color: 'var(--text-primary)' }}>Overall Business Health</h4>
            <div style={{ fontSize: '14px', fontWeight: '600', color: 'var(--text-primary)' }}>{payload.overall_health}</div>
          </div>
        )}

        {payload.executive_summary && payload.executive_summary.length > 0 && (
          <div style={{ marginBottom: '20px' }}>
             <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: 'var(--text-primary)' }}>Executive Summary</h4>
             <ul style={{ margin: 0, paddingLeft: '16px', color: 'var(--text-secondary)', fontSize: '12px', lineHeight: '1.5' }}>
               {payload.executive_summary.map((txt, idx) => (
                 <li key={idx} style={{ marginBottom: '4px' }}>{txt}</li>
               ))}
             </ul>
          </div>
        )}

        {payload.kpis && payload.kpis.length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: 'var(--text-primary)' }}>Key Metrics</h4>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(120px, 1fr))', gap: '8px' }}>
              {payload.kpis.map((kpi, idx) => (
                <div key={idx} style={{ background: 'var(--bg-hover)', padding: '10px', borderRadius: '6px', border: '1px solid var(--border)' }}>
                  <div style={{ fontSize: '11px', color: 'var(--text-secondary)', marginBottom: '4px' }}>{kpi.label}</div>
                  <div style={{ fontSize: '14px', fontWeight: '600', color: 'var(--text-primary)' }}>{kpi.value}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {payload.department_performance && payload.department_performance.length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: 'var(--text-primary)' }}>Department Performance</h4>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {payload.department_performance.map((dept, idx) => {
                 let color = 'var(--text-secondary)';
                 let bg = 'var(--bg-hover)';
                 let border = 'var(--border)';
                 
                 if (dept.status && (dept.status.toLowerCase().includes('excellent') || dept.status.toLowerCase().includes('good') || dept.status.toLowerCase().includes('healthy'))) {
                    color = '#10b981'; // green
                    bg = 'rgba(16, 185, 129, 0.1)';
                    border = 'rgba(16, 185, 129, 0.2)';
                 } else if (dept.status && (dept.status.toLowerCase().includes('attention') || dept.status.toLowerCase().includes('warning') || dept.status.toLowerCase().includes('slow'))) {
                    color = '#f59e0b'; // orange
                    bg = 'rgba(245, 158, 11, 0.1)';
                    border = 'rgba(245, 158, 11, 0.2)';
                 } else if (dept.status && (dept.status.toLowerCase().includes('critical') || dept.status.toLowerCase().includes('poor'))) {
                    color = '#ef4444'; // red
                    bg = 'rgba(239, 68, 68, 0.1)';
                    border = 'rgba(239, 68, 68, 0.2)';
                 }

                 return (
                  <div key={idx} style={{ 
                    padding: '4px 8px', borderRadius: '4px', fontSize: '11px', fontWeight: 500,
                    background: bg, color: color, border: `1px solid ${border}`, display: 'flex', gap: '4px'
                  }}>
                    <span style={{ color: 'var(--text-primary)' }}>{dept.department}:</span> {dept.status}
                  </div>
                 )
              })}
            </div>
          </div>
        )}

        {payload.ai_insights && payload.ai_insights.length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Lightbulb size={14} color="var(--accent)" /> AI Insights
            </h4>
            <ul style={{ margin: 0, paddingLeft: '16px', color: 'var(--text-secondary)', fontSize: '12px', lineHeight: '1.5' }}>
              {payload.ai_insights.map((insight, idx) => (
                <li key={idx} style={{ marginBottom: '4px' }}>{insight}</li>
              ))}
            </ul>
          </div>
        )}

        {payload.business_risks && payload.business_risks.length > 0 && (
          <div style={{ marginBottom: '20px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: '#ef4444', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <AlertCircle size={14} color="#ef4444" /> Business Risks
            </h4>
            <ul style={{ margin: 0, paddingLeft: '16px', color: 'var(--text-secondary)', fontSize: '12px', lineHeight: '1.5' }}>
              {payload.business_risks.map((risk, idx) => (
                <li key={idx} style={{ marginBottom: '4px' }}>{risk}</li>
              ))}
            </ul>
          </div>
        )}

        {payload.recommended_actions && payload.recommended_actions.length > 0 && (
          <div style={{ marginBottom: '8px' }}>
            <h4 style={{ margin: '0 0 8px 0', fontSize: '13px', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: '6px' }}>
              <CheckCircle2 size={14} color="var(--accent)" /> Recommended Actions
            </h4>
            <ul style={{ margin: 0, paddingLeft: '16px', color: 'var(--text-secondary)', fontSize: '12px', lineHeight: '1.5' }}>
              {payload.recommended_actions.map((action, idx) => (
                <li key={idx} style={{ marginBottom: '4px' }}>{action}</li>
              ))}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

export default BusinessSummaryCard;
